apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-config
  namespace: strapi
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "1337"
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: "10.43.98.134"
  DATABASE_NAME: "shipitlive"
  DATABASE_PORT: "5432"
  DATABASE_SSL: "false"

