apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi-ingress
  namespace: strapi
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure  # Added 'web' entrypoint for HTTP
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/hsts-max-age: "31536000"
    traefik.ingress.kubernetes.io/hsts-include-subdomains: "true"
    traefik.ingress.kubernetes.io/hsts-preload: "true"
    traefik.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: admin.shipitlive.dev
    http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: Prefix
        backend:
          service:
            name: strapi
            port:
              number: 1337  # Route ACME challenge to port 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: strapi
            port:
              number: 1337  # Keep routing app traffic to port 1337
  tls:
  - hosts:
    - admin.shipitlive.dev
    secretName: my-tls-secret

