apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: shipitlive/strapy-service:v1
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: "production"

            # Security-related secrets
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: ADMIN_JWT_SECRET
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: API_TOKEN_SALT
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: APP_KEYS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: JWT_SECRET
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: TRANSFER_TOKEN_SALT

            # Database connection settings
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: DATABASE_URL
            - name: DATABASE_CLIENT
              value: "postgres" # Directly specifying as it's a constant
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_PORT
              value: "5432" # Default PostgreSQL port, no need to fetch from secret
            - name: DATABASE_SSL
              value: "false" # Hardcoding as per provided values

            # Strapi-specific settings
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"

          volumeMounts:
            - name: strapi-data
              mountPath: /shipitlive_strapi/public/uploads
      volumes:
        - name: strapi-data
          persistentVolumeClaim:
            claimName: strapi-pvc
