apiVersion: v1
kind: Secret
metadata:
  name: strapi-secret
  namespace: strapi
type: Opaque
data:
  ADMIN_JWT_SECRET: x9IEKWH/ove82W3khrrqtw==
  API_TOKEN_SALT: P5hg6B08TXYTsKjAyOKkcQ==
  APP_KEYS: g1BU3h6cSfUFMCzQjbcQOQ==,5b2p71623Nwv5VQZKWf18g==,0+rJQkLKf6/Mbr8mlreZHA==,hfnp5fGxVKEsVEB8dkiqpA==
  DATABASE_URL: cG9zdGdyZXNxbDovL3NoaXBpdGxpdmU6c2hpcGl0bGl2ZUBwb3N0Z3Jlcy1zdHJhcGktcG9zdGdyZXNxbDo1NDMyL3N0cmFwaQ==
  DATABASE_CLIENT: cG9zdGdyZXM=
  DATABASE_HOST: cG9zdGdyZXMtc3RyYXBpLXBvc3RncmVzcWwK
  DATABASE_NAME: c3RyYXBpCg==
  DATABASE_PASSWORD: c2hpcGl0bGl2ZQo=
  DATABASE_PORT: NTQzMgo=
  DATABASE_SSL: ZmFsc2U=
  DATABASE_USERNAME: c2hpcGl0bGl2ZQ==
  HOST: MC4wLjAuMA==
  JWT_SECRET: qI8xOj8O92CyRtAhellxrg==
  PORT: MTMzNw==
  TRANSFER_TOKEN_SALT: t7L+h3f0ast3KauA5Y++sg==
