apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp
  namespace: strapi
spec:
  secretName: webapp-secret
  dnsNames:
    - admin.shipitlive.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
