apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: shipitlive/strapi-service:v1
          ports:
            - containerPort: 1337
          envFrom:
            - configMapRef:
                name: strapi-config
            - secretRef:
                name: strapi-secret
          volumeMounts:
            - name: strapi-data
              mountPath: /srv/app
      volumes:
        - name: strapi-data
          persistentVolumeClaim:
            claimName: strapi-pvc

